project:
  type: website
  output-dir: docs

website:
  title: "SQL for Accounting Analytics"
  page-navigation: true
  navbar:
    search: true
  sidebar:
    style: "floating"
    search: true
    title: "Contents"
    contents:
      - index.qmd
      - section: "Relational Databases"
        contents:
          - tables.qmd
          - keys.qmd
          - relationships.qmd
          - normalization.qmd
          - structure.qmd
      - section: "SQL Scripts"
        contents:
          - connection.qmd
          - scripts.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



